# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "public_network", ip: "192.168.1.100"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nodejs
    apt-get install -y npm
    cd /vagrant/web
    npm install
  SHELL
end
