# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  #config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", ip: "192.168.1.171"
  config.vm.synced_folder "./", "/development", type: "rsync"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y git
     apt-get install -y mosquitto mosquitto-clients
  SHELL
end
